import "./globals.css";
import { Playfair_Display, Source_Sans_3 } from "next/font/google";
import Footer from "./_components/Footer";

//const inter = Inter({ subsets: ["latin"] });
//const playfair = Playfair_Display({ subsets: ["latin"] });
//const source = Source_Sans_3({ subsets: ["latin"] });

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--display-font",
});

const source = Source_Sans_3({
  subsets: ["latin"],
  variable: "--body-font",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${playfair.variable} ${source.variable}`}>
        {/* nav */}
        <div className="text-dark font-body">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
